# Generated by Django 4.1.3 on 2023-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sokoban', '0002_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
