# Generated by Django 4.1.3 on 2023-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokoban', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
